import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root',
})
export class ItemMap {
  public map: any;

  /* Defaults */
  public seed = 1658699457335;
  public critical_list = [
    'bastion_treasure',
    'blaze',
    'enderman',
    'stronghold_library',
    'lava_cauldron',
    'end_city_treasure',
    'diamond_ore',
    'diamond_block',
    'torch',
    'netherite_block',
    'emerald_ore',
    'emerald_block',
  ];
  public secondary_list = [''];

  public alternative_map = {
    cauldron: ['lava_cauldron', 'iron'],
    dark_oak_wood: ['dark_oak_log'],
    netherite_block: [],
  };

  constructor() {
    if (localStorage['sourceText']) {
      this.initialize(localStorage['sourceText']);
    } else {
      this.initialize();
    }
  }

  initialize(source: string = this.txt) {
    this.txt = source;
    localStorage['sourceText'] = source;
    let list = Array.from(source.matchAll(/(\w*) drops from (.*)/g)).map((x) =>
      x.splice(1)
    );
    // console.log('list is', list);
    this.map = {};
    for (let i = 0; i < list.length; i++) {
      this.map[list[i][0]] = list[i][1];
    }
  }

  txt = `This file tells you which drops come from where.
  Please Note: This file grabs the ENTIRE list of the used seed, regardless of which options you enabled/disabled.
  
  acacia_button drops from cobweb
  acacia_door drops from sandstone
  acacia_fence drops from warped_roots
  acacia_fence_gate drops from shulker
  acacia_leaves drops from sugar_cane
  acacia_log drops from gilded_blackstone
  acacia_planks drops from warped_fence_gate
  acacia_pressure_plate drops from deepslate_brick_slab
  acacia_sapling drops from deepslate_tile_stairs
  acacia_sign drops from mangrove_button
  acacia_slab drops from honeycomb_block
  acacia_stairs drops from carved_pumpkin
  acacia_trapdoor drops from fire_coral
  acacia_wood drops from green
  activator_rail drops from glow_lichen
  allium drops from warden
  amethyst_block drops from dead_bush
  amethyst_cluster drops from wolf
  ancient_debris drops from sand
  andesite drops from petrified_oak_slab
  andesite_slab drops from fletching_table
  andesite_stairs drops from potted_birch_sapling
  andesite_wall drops from wheat
  anvil drops from bastion_other
  attached_melon_stem drops from waxed_cut_copper_stairs
  attached_pumpkin_stem drops from jungle_log
  azalea drops from white_banner
  azalea_leaves drops from yellow_terracotta
  azure_bluet drops from purple_stained_glass_pane
  bamboo drops from bubble_coral
  bamboo_sapling drops from potted_spruce_sapling
  barrel drops from dandelion
  basalt drops from pink
  beacon drops from red_nether_brick_wall
  beehive drops from jungle_temple
  beetroots drops from packed_ice
  bee_nest drops from deepslate_redstone_ore
  bell drops from magenta
  big_dripleaf drops from blue_terracotta
  big_dripleaf_stem drops from potted_jungle_sapling
  birch_button drops from podzol
  birch_door drops from mud_bricks
  birch_fence drops from chiseled_polished_blackstone
  birch_fence_gate drops from blue_candle
  birch_leaves drops from mangrove_log
  birch_log drops from light_blue_glazed_terracotta
  birch_planks drops from enderman
  birch_pressure_plate drops from village_cartographer
  birch_sapling drops from stronghold_crossing
  birch_sign drops from packed_mud
  birch_slab drops from pumpkin_stem
  birch_stairs drops from magenta_glazed_terracotta
  birch_trapdoor drops from nether_wart
  birch_wood drops from pink_terracotta
  blackstone drops from cobblestone_slab
  blackstone_slab drops from end_stone_brick_stairs
  blackstone_stairs drops from blaze
  blackstone_wall drops from lapis_ore
  black_banner drops from cobblestone_stairs
  black_bed drops from stone_brick_stairs
  black_candle drops from lime_banner
  black_candle_cake drops from chiseled_sandstone
  black_carpet drops from polished_blackstone_wall
  black_concrete drops from light_gray_bed
  black_concrete_powder drops from junk
  black_glazed_terracotta drops from kelp_plant
  black_stained_glass drops from weathered_cut_copper
  black_stained_glass_pane drops from andesite_slab
  black_terracotta drops from abandoned_mineshaft
  black_wool drops from potted_warped_fungus
  blast_furnace drops from cobblestone_wall
  blue_banner drops from dirt_path
  blue_bed drops from yellow_candle
  blue_candle drops from dragon_egg
  blue_candle_cake drops from black_glazed_terracotta
  blue_carpet drops from deepslate_brick_stairs
  blue_concrete drops from gray_wool
  blue_concrete_powder drops from cobblestone
  blue_glazed_terracotta drops from dark_oak_sapling
  blue_ice drops from lava_cauldron
  blue_orchid drops from emerald_block
  blue_stained_glass drops from stone_slab
  blue_stained_glass_pane drops from dead_horn_coral_fan
  blue_terracotta drops from oak_door
  blue_wool drops from quartz_pillar
  bone_block drops from stripped_warped_stem
  bookshelf drops from piglin_brute
  brain_coral drops from dark_oak_fence
  brain_coral_block drops from farmland
  brain_coral_fan drops from waxed_exposed_cut_copper
  brewing_stand drops from polished_diorite_stairs
  bricks drops from weeping_vines_plant
  brick_slab drops from potted_orange_tulip
  brick_stairs drops from kelp
  brick_wall drops from gray
  brown_banner drops from witch
  brown_bed drops from polished_blackstone_brick_stairs
  brown_candle drops from attached_pumpkin_stem
  brown_candle_cake drops from moss_carpet
  brown_carpet drops from chest
  brown_concrete drops from cut_red_sandstone_slab
  brown_concrete_powder drops from smoker
  brown_glazed_terracotta drops from potted_acacia_sapling
  brown_mushroom drops from light_gray_stained_glass_pane
  brown_mushroom_block drops from potted_white_tulip
  brown_stained_glass drops from sculk_shrieker
  brown_stained_glass_pane drops from jungle_fence_gate
  brown_terracotta drops from light_blue_candle_cake
  brown_wool drops from dark_oak_pressure_plate
  bubble_coral drops from glowstone
  bubble_coral_block drops from village_butcher
  bubble_coral_fan drops from nether_brick_stairs
  budding_amethyst drops from red_nether_bricks
  cactus drops from oxidized_cut_copper_stairs
  cake drops from deepslate_lapis_ore
  calcite drops from spore_blossom
  campfire drops from skeleton
  candle drops from detector_rail
  candle_cake drops from lectern
  carrots drops from gray_candle_cake
  cartography_table drops from potted_azure_bluet
  carved_pumpkin drops from mud
  cauldron drops from warped_stem
  cave_vines drops from potted_crimson_roots
  cave_vines_plant drops from blue_orchid
  chain drops from dark_oak_leaves
  chest drops from blackstone_slab
  chipped_anvil drops from acacia_slab
  chiseled_deepslate drops from blast_furnace
  chiseled_nether_bricks drops from coal_ore
  chiseled_polished_blackstone drops from armor_stand
  chiseled_quartz_block drops from cyan_stained_glass_pane
  chiseled_red_sandstone drops from potted_mangrove_propagule
  chiseled_sandstone drops from diorite_wall
  chiseled_stone_bricks drops from red_banner
  chorus_flower drops from potted_lily_of_the_valley
  chorus_plant drops from emerald_ore
  clay drops from village_toolsmith
  coal_block drops from white_candle_cake
  coal_ore drops from andesite
  coarse_dirt drops from jungle_wood
  cobbled_deepslate drops from lime_glazed_terracotta
  cobbled_deepslate_slab drops from gray_concrete
  cobbled_deepslate_stairs drops from ancient_city_ice_box
  cobbled_deepslate_wall drops from stripped_dark_oak_wood
  cobblestone drops from cleric_gift
  cobblestone_slab drops from stonecutter
  cobblestone_stairs drops from lantern
  cobblestone_wall drops from granite_slab
  cobweb drops from gray_terracotta
  cocoa drops from brick_slab
  comparator drops from acacia_trapdoor
  composter drops from weathered_copper
  conduit drops from brown_carpet
  copper_block drops from composter
  copper_ore drops from redstone_ore
  cornflower drops from orange_stained_glass_pane
  cracked_deepslate_bricks drops from polished_granite
  cracked_deepslate_tiles drops from terracotta
  cracked_nether_bricks drops from pointed_dripstone
  cracked_polished_blackstone_bricks drops from ladder
  cracked_stone_bricks drops from player_head
  crafting_table drops from dead_fire_coral_block
  creeper_head drops from brown_concrete
  crimson_button drops from nether_bricks
  crimson_door drops from orange_bed
  crimson_fence drops from cartographer_gift
  crimson_fence_gate drops from orange_banner
  crimson_fungus drops from spruce_log
  crimson_hyphae drops from blue_banner
  crimson_nylium drops from guardian
  crimson_planks drops from pink_concrete_powder
  crimson_pressure_plate drops from armorer_gift
  crimson_roots drops from chiseled_stone_bricks
  crimson_sign drops from oak_button
  crimson_slab drops from birch_planks
  crimson_stairs drops from enchanting_table
  crimson_stem drops from infested_stone
  crimson_trapdoor drops from calcite
  crying_obsidian drops from birch_stairs
  cut_copper drops from yellow_banner
  cut_copper_slab drops from red_mushroom
  cut_copper_stairs drops from torch
  cut_red_sandstone drops from acacia_sign
  cut_red_sandstone_slab drops from black_wool
  cut_sandstone drops from green_candle_cake
  cut_sandstone_slab drops from acacia_fence_gate
  cyan_banner drops from cornflower
  cyan_bed drops from purpur_block
  cyan_candle drops from lime_terracotta
  cyan_candle_cake drops from pufferfish
  cyan_carpet drops from blackstone
  cyan_concrete drops from deepslate_coal_ore
  cyan_concrete_powder drops from cat
  cyan_glazed_terracotta drops from dark_oak_slab
  cyan_stained_glass drops from dark_oak_button
  cyan_stained_glass_pane drops from cobbled_deepslate_wall
  cyan_terracotta drops from magenta_concrete_powder
  cyan_wool drops from cracked_nether_bricks
  damaged_anvil drops from crimson_hyphae
  dandelion drops from cake
  dark_oak_button drops from mule
  dark_oak_door drops from brown_candle
  dark_oak_fence drops from birch_sapling
  dark_oak_fence_gate drops from warped_stairs
  dark_oak_leaves drops from dead_brain_coral
  dark_oak_log drops from sweet_berry_bush
  dark_oak_planks drops from smooth_quartz
  dark_oak_pressure_plate drops from blue_bed
  dark_oak_sapling drops from warped_slab
  dark_oak_sign drops from respawn_anchor
  dark_oak_slab drops from sandstone_wall
  dark_oak_stairs drops from cyan_banner
  dark_oak_trapdoor drops from potted_oak_sapling
  dark_oak_wood drops from potted_dark_oak_sapling
  dark_prismarine drops from mooshroom
  dark_prismarine_slab drops from oxidized_copper
  dark_prismarine_stairs drops from stripped_dark_oak_log
  daylight_detector drops from light_blue_bed
  dead_brain_coral drops from allium
  dead_brain_coral_block drops from snow_golem
  dead_brain_coral_fan drops from crimson_fence
  dead_bubble_coral drops from village_plains_house
  dead_bubble_coral_block drops from purple_terracotta
  dead_bubble_coral_fan drops from soul_fire
  dead_bush drops from barrel
  dead_fire_coral drops from white_wool
  dead_fire_coral_block drops from rabbit
  dead_fire_coral_fan drops from ender_chest
  dead_horn_coral drops from dried_kelp_block
  dead_horn_coral_block drops from yellow_stained_glass_pane
  dead_horn_coral_fan drops from soul_sand
  dead_tube_coral drops from potted_warped_roots
  dead_tube_coral_block drops from rooted_dirt
  dead_tube_coral_fan drops from black_carpet
  deepslate drops from magenta_wool
  deepslate_bricks drops from bastion_hoglin_stable
  deepslate_brick_slab drops from smooth_sandstone
  deepslate_brick_stairs drops from tnt
  deepslate_brick_wall drops from bookshelf
  deepslate_coal_ore drops from lever
  deepslate_copper_ore drops from light_gray_wool
  deepslate_diamond_ore drops from squid
  deepslate_emerald_ore drops from dark_prismarine_slab
  deepslate_gold_ore drops from waxed_oxidized_cut_copper
  deepslate_iron_ore drops from birch_sign
  deepslate_lapis_ore drops from yellow_wool
  deepslate_redstone_ore drops from cyan_concrete_powder
  deepslate_tiles drops from lime_candle
  deepslate_tile_slab drops from netherrack
  deepslate_tile_stairs drops from village_fisher
  deepslate_tile_wall drops from dark_prismarine_stairs
  detector_rail drops from dead_bubble_coral_block
  diamond_block drops from jungle_sign
  diamond_ore drops from mangrove_door
  diorite drops from iron_block
  diorite_slab drops from nether_bridge
  diorite_stairs drops from panda
  diorite_wall drops from bee_nest
  dirt drops from village_desert_house
  dirt_path drops from red
  dispenser drops from mycelium
  dragon_egg drops from gray_glazed_terracotta
  dragon_head drops from hopper
  dried_kelp_block drops from cauldron
  dripstone_block drops from oak_trapdoor
  dropper drops from nether_brick_wall
  emerald_block drops from oak_pressure_plate
  emerald_ore drops from dead_tube_coral
  enchanting_table drops from stone_bricks
  ender_chest drops from melon
  end_rod drops from target
  end_stone drops from end_stone_brick_slab
  end_stone_bricks drops from crimson_fence_gate
  end_stone_brick_slab drops from powder_snow
  end_stone_brick_stairs drops from melon_stem
  end_stone_brick_wall drops from llama
  exposed_copper drops from weathered_cut_copper_stairs
  exposed_cut_copper drops from blue_concrete
  exposed_cut_copper_slab drops from weaponsmith_gift
  exposed_cut_copper_stairs drops from potted_pink_tulip
  farmland drops from fern
  fern drops from waxed_weathered_cut_copper_stairs
  fire drops from spawn_bonus_chest
  fire_coral drops from light_gray_banner
  fire_coral_block drops from granite_stairs
  fire_coral_fan drops from brain_coral_block
  fletching_table drops from light_blue_stained_glass_pane
  flowering_azalea drops from jungle_fence
  flowering_azalea_leaves drops from dolphin
  flower_pot drops from green_stained_glass
  frogspawn drops from warped_fungus
  frosted_ice drops from deepslate_diamond_ore
  furnace drops from gray_carpet
  gilded_blackstone drops from flowering_azalea
  glass drops from magenta_stained_glass_pane
  glass_pane drops from stronghold_corridor
  glowstone drops from mossy_cobblestone
  glow_lichen drops from deepslate_tile_wall
  gold_block drops from cod
  gold_ore drops from potted_crimson_fungus
  granite drops from desert_pyramid
  granite_slab drops from dark_oak_wood
  granite_stairs drops from spruce_slab
  granite_wall drops from orange_terracotta
  grass drops from smooth_sandstone_stairs
  grass_block drops from bell
  gravel drops from small_amethyst_bud
  gray_banner drops from evoker
  gray_bed drops from black_banner
  gray_candle drops from green_glazed_terracotta
  gray_candle_cake drops from weeping_vines
  gray_carpet drops from cartography_table
  gray_concrete drops from black_stained_glass
  gray_concrete_powder drops from moss_block
  gray_glazed_terracotta drops from fox
  gray_stained_glass drops from bat
  gray_stained_glass_pane drops from red_carpet
  gray_terracotta drops from black_terracotta
  gray_wool drops from crimson_roots
  green_banner drops from birch_trapdoor
  green_bed drops from lime_stained_glass
  green_candle drops from allay
  green_candle_cake drops from oxidized_cut_copper_slab
  green_carpet drops from cobbled_deepslate_slab
  green_concrete drops from lime_candle_cake
  green_concrete_powder drops from underwater_ruin_big
  green_glazed_terracotta drops from granite_wall
  green_stained_glass drops from sticky_piston
  green_stained_glass_pane drops from anvil
  green_terracotta drops from light_blue_concrete
  green_wool drops from orange
  grindstone drops from crimson_stairs
  hanging_roots drops from turtle
  hay_block drops from cut_copper
  heavy_weighted_pressure_plate drops from spawner
  honeycomb_block drops from redstone_lamp
  honey_block drops from cyan_candle_cake
  hopper drops from diorite_stairs
  horn_coral drops from red_nether_brick_stairs
  horn_coral_block drops from gray_concrete_powder
  horn_coral_fan drops from end_stone
  ice drops from sandstone_slab
  infested_chiseled_stone_bricks drops from pearlescent_froglight
  infested_cobblestone drops from warped_nylium
  infested_cracked_stone_bricks drops from frosted_ice
  infested_deepslate drops from spruce_sapling
  infested_mossy_stone_bricks drops from horse
  infested_stone drops from yellow_carpet
  infested_stone_bricks drops from exposed_cut_copper_slab
  iron_bars drops from brown_concrete_powder
  iron_block drops from ocelot
  iron_door drops from village_tannery
  iron_ore drops from oak_slab
  iron_trapdoor drops from crying_obsidian
  jack_o_lantern drops from purple_banner
  jukebox drops from purple_concrete_powder
  jungle_button drops from nether_quartz_ore
  jungle_door drops from treasure
  jungle_fence drops from jungle_trapdoor
  jungle_fence_gate drops from dark_oak_door
  jungle_leaves drops from furnace
  jungle_log drops from cobbled_deepslate_stairs
  jungle_planks drops from village_weaponsmith
  jungle_pressure_plate drops from potted_brown_mushroom
  jungle_sapling drops from mossy_stone_brick_stairs
  jungle_sign drops from pillager
  jungle_slab drops from horn_coral
  jungle_stairs drops from piston
  jungle_trapdoor drops from prismarine_brick_stairs
  jungle_wood drops from green_terracotta
  kelp drops from brown_mushroom
  kelp_plant drops from infested_deepslate
  ladder drops from lime_bed
  lantern drops from tube_coral_fan
  lapis_block drops from amethyst_cluster
  lapis_ore drops from prismarine_slab
  large_amethyst_bud drops from oxidized_cut_copper
  large_fern drops from nether_sprouts
  lava_cauldron drops from white_stained_glass
  lectern drops from spruce_planks
  lever drops from lime
  lightning_rod drops from light_blue_wool
  light_blue_banner drops from stone_stairs
  light_blue_bed drops from green_wool
  light_blue_candle drops from drowned
  light_blue_candle_cake drops from warped_hyphae
  light_blue_carpet drops from wandering_trader
  light_blue_concrete drops from orange_concrete_powder
  light_blue_concrete_powder drops from white_candle
  light_blue_glazed_terracotta drops from village_mason
  light_blue_stained_glass drops from grass_block
  light_blue_stained_glass_pane drops from tadpole
  light_blue_terracotta drops from stripped_spruce_wood
  light_blue_wool drops from brown_stained_glass_pane
  light_gray_banner drops from scaffolding
  light_gray_bed drops from chiseled_quartz_block
  light_gray_candle drops from potted_poppy
  light_gray_candle_cake drops from warped_sign
  light_gray_carpet drops from diorite
  light_gray_concrete drops from amethyst_block
  light_gray_concrete_powder drops from horn_coral_fan
  light_gray_glazed_terracotta drops from poppy
  light_gray_stained_glass drops from red_concrete_powder
  light_gray_stained_glass_pane drops from shipwreck_treasure
  light_gray_terracotta drops from birch_fence_gate
  light_gray_wool drops from acacia_sapling
  light_weighted_pressure_plate drops from infested_chiseled_stone_bricks
  lilac drops from cave_vines_plant
  lily_of_the_valley drops from red_candle_cake
  lily_pad drops from smooth_quartz_slab
  lime_banner drops from sandstone_stairs
  lime_bed drops from yellow
  lime_candle drops from loom
  lime_candle_cake drops from green_concrete_powder
  lime_carpet drops from white_carpet
  lime_concrete drops from vindicator
  lime_concrete_powder drops from iron_ore
  lime_glazed_terracotta drops from honey_block
  lime_stained_glass drops from infested_cracked_stone_bricks
  lime_stained_glass_pane drops from red_stained_glass
  lime_terracotta drops from mangrove_fence_gate
  lime_wool drops from oak_sapling
  lodestone drops from gold_ore
  loom drops from azure_bluet
  magenta_banner drops from bubble_coral_fan
  magenta_bed drops from stone_button
  magenta_candle drops from crimson_button
  magenta_candle_cake drops from village_shepherd
  magenta_carpet drops from prismarine_stairs
  magenta_concrete drops from spruce_button
  magenta_concrete_powder drops from blackstone_wall
  magenta_glazed_terracotta drops from bamboo_sapling
  magenta_stained_glass drops from wet_sponge
  magenta_stained_glass_pane drops from husk
  magenta_terracotta drops from attached_melon_stem
  magenta_wool drops from red_stained_glass_pane
  magma_block drops from red_sand
  mangrove_button drops from birch_leaves
  mangrove_door drops from polished_basalt
  mangrove_fence drops from spider
  mangrove_fence_gate drops from mushroom_stem
  mangrove_leaves drops from crimson_slab
  mangrove_log drops from candle_cake
  mangrove_planks drops from dark_oak_fence_gate
  mangrove_pressure_plate drops from yellow_candle_cake
  mangrove_propagule drops from dark_oak_planks
  mangrove_roots drops from blackstone_stairs
  mangrove_sign drops from polished_blackstone_bricks
  mangrove_slab drops from mud_brick_wall
  mangrove_stairs drops from diamond_ore
  mangrove_trapdoor drops from redstone_block
  mangrove_wood drops from polished_blackstone_pressure_plate
  medium_amethyst_bud drops from jungle_button
  melon drops from black_candle_cake
  melon_stem drops from muddy_mangrove_roots
  mossy_cobblestone drops from zombie_head
  mossy_cobblestone_slab drops from deepslate_tile_slab
  mossy_cobblestone_stairs drops from lapis_block
  mossy_cobblestone_wall drops from dead_brain_coral_fan
  mossy_stone_bricks drops from chiseled_deepslate
  mossy_stone_brick_slab drops from gray_bed
  mossy_stone_brick_stairs drops from waxed_weathered_cut_copper_slab
  mossy_stone_brick_wall drops from warped_wart_block
  moss_block drops from mangrove_stairs
  moss_carpet drops from waxed_oxidized_copper
  mud drops from dark_oak_sign
  muddy_mangrove_roots drops from bastion_bridge
  mud_bricks drops from oak_wood
  mud_brick_slab drops from creeper
  mud_brick_stairs drops from goat
  mud_brick_wall drops from zombie_villager
  mushroom_stem drops from mossy_cobblestone_stairs
  mycelium drops from red_bed
  netherite_block drops from blue_glazed_terracotta
  netherrack drops from magenta_terracotta
  nether_bricks drops from stripped_crimson_stem
  nether_brick_fence drops from white_concrete
  nether_brick_slab drops from pink_stained_glass_pane
  nether_brick_stairs drops from big_dripleaf
  nether_brick_wall drops from dead_horn_coral_block
  nether_gold_ore drops from soul_soil
  nether_portal drops from tripwire_hook
  nether_quartz_ore drops from silverfish
  nether_sprouts drops from copper_block
  nether_wart drops from gray_stained_glass_pane
  nether_wart_block drops from brown_terracotta
  note_block drops from polished_granite_stairs
  oak_button drops from shepherd_gift
  oak_door drops from pink_tulip
  oak_fence drops from white_concrete_powder
  oak_fence_gate drops from acacia_leaves
  oak_leaves drops from woodland_mansion
  oak_log drops from light_gray_carpet
  oak_planks drops from nether_brick_slab
  oak_pressure_plate drops from sculk_catalyst
  oak_sapling drops from polished_deepslate
  oak_sign drops from brown_stained_glass
  oak_slab drops from obsidian
  oak_stairs drops from pink_candle_cake
  oak_trapdoor drops from coal_block
  oak_wood drops from village_savanna_house
  observer drops from quartz_stairs
  obsidian drops from turtle_egg
  ochre_froglight drops from polished_deepslate_stairs
  orange_banner drops from jungle_planks
  orange_bed drops from polished_andesite
  orange_candle drops from deepslate_copper_ore
  orange_candle_cake drops from orange_stained_glass
  orange_carpet drops from peony
  orange_concrete drops from oak_sign
  orange_concrete_powder drops from exposed_cut_copper_stairs
  orange_glazed_terracotta drops from purple_glazed_terracotta
  orange_stained_glass drops from spruce_leaves
  orange_stained_glass_pane drops from cracked_deepslate_bricks
  orange_terracotta drops from diamond_block
  orange_tulip drops from cyan_stained_glass
  orange_wool drops from light_gray_concrete_powder
  oxeye_daisy drops from stone_brick_slab
  oxidized_copper drops from horn_coral_block
  oxidized_cut_copper drops from flower_pot
  oxidized_cut_copper_slab drops from stripped_mangrove_wood
  oxidized_cut_copper_stairs drops from white_bed
  packed_ice drops from oak_stairs
  packed_mud drops from frog
  pearlescent_froglight drops from andesite_stairs
  peony drops from potatoes
  petrified_oak_slab drops from end_rod
  pink_banner drops from beetroots
  pink_bed drops from orange_concrete
  pink_candle drops from jukebox
  pink_candle_cake drops from gravel
  pink_carpet drops from hoglin
  pink_concrete drops from lodestone
  pink_concrete_powder drops from spruce_stairs
  pink_glazed_terracotta drops from fish
  pink_stained_glass drops from pig
  pink_stained_glass_pane drops from spruce_trapdoor
  pink_terracotta drops from bastion_treasure
  pink_tulip drops from dead_fire_coral_fan
  pink_wool drops from zombified_piglin
  piston drops from blue_stained_glass_pane
  player_head drops from quartz_bricks
  podzol drops from spruce_fence
  pointed_dripstone drops from red_candle
  polished_andesite drops from basalt
  polished_andesite_slab drops from stripped_mangrove_log
  polished_andesite_stairs drops from dark_oak_log
  polished_basalt drops from exposed_cut_copper
  polished_blackstone drops from chorus_plant
  polished_blackstone_bricks drops from spruce_wood
  polished_blackstone_brick_slab drops from light_gray_terracotta
  polished_blackstone_brick_stairs drops from fishing
  polished_blackstone_brick_wall drops from dark_oak_trapdoor
  polished_blackstone_button drops from potted_oxeye_daisy
  polished_blackstone_pressure_plate drops from yellow_stained_glass
  polished_blackstone_slab drops from underwater_ruin_small
  polished_blackstone_stairs drops from iron_door
  polished_blackstone_wall drops from redstone_torch
  polished_deepslate drops from dark_prismarine
  polished_deepslate_slab drops from cut_sandstone
  polished_deepslate_stairs drops from prismarine_brick_slab
  polished_deepslate_wall drops from lilac
  polished_diorite drops from glass
  polished_diorite_slab drops from potted_dandelion
  polished_diorite_stairs drops from jungle_slab
  polished_granite drops from pink_candle
  polished_granite_slab drops from warped_planks
  polished_granite_stairs drops from redstone_wire
  poppy drops from black_stained_glass_pane
  potatoes drops from polar_bear
  potted_acacia_sapling drops from granite
  potted_allium drops from andesite_wall
  potted_azalea_bush drops from brown_bed
  potted_azure_bluet drops from ancient_debris
  potted_bamboo drops from red_nether_brick_slab
  potted_birch_sapling drops from polished_blackstone_brick_wall
  potted_blue_orchid drops from brain_coral
  potted_brown_mushroom drops from mangrove_sign
  potted_cactus drops from mossy_stone_brick_wall
  potted_cornflower drops from jungle_pressure_plate
  potted_crimson_fungus drops from jack_o_lantern
  potted_crimson_roots drops from dragon_head
  potted_dandelion drops from mangrove_roots
  potted_dark_oak_sapling drops from village_armorer
  potted_dead_bush drops from rose_bush
  potted_fern drops from bamboo
  potted_flowering_azalea_bush drops from hanging_roots
  potted_jungle_sapling drops from waxed_cut_copper
  potted_lily_of_the_valley drops from yellow_concrete_powder
  potted_mangrove_propagule drops from mangrove_trapdoor
  potted_oak_sapling drops from waxed_exposed_copper
  potted_orange_tulip drops from cyan_carpet
  potted_oxeye_daisy drops from crafting_table
  potted_pink_tulip drops from gray_banner
  potted_poppy drops from green_carpet
  potted_red_mushroom drops from light_gray_stained_glass
  potted_red_tulip drops from cactus
  potted_spruce_sapling drops from tall_seagrass
  potted_warped_fungus drops from shroomlight
  potted_warped_roots drops from acacia_stairs
  potted_white_tulip drops from dead_tube_coral_fan
  potted_wither_rose drops from stripped_birch_wood
  powder_snow drops from pink_concrete
  powder_snow_cauldron drops from stone_brick_wall
  powered_rail drops from infested_mossy_stone_bricks
  prismarine drops from smithing_table
  prismarine_bricks drops from zombie
  prismarine_brick_slab drops from black_bed
  prismarine_brick_stairs drops from mossy_stone_brick_slab
  prismarine_slab drops from village_fletcher
  prismarine_stairs drops from sponge
  prismarine_wall drops from light_gray_candle
  pumpkin drops from soul_campfire
  pumpkin_stem drops from polished_deepslate_wall
  purple_banner drops from cracked_polished_blackstone_bricks
  purple_bed drops from light_gray
  purple_candle drops from pink_wool
  purple_candle_cake drops from dead_bubble_coral
  purple_carpet drops from crimson_door
  purple_concrete drops from brown_banner
  purple_concrete_powder drops from endermite
  purple_glazed_terracotta drops from zombie_horse
  purple_stained_glass drops from magenta_bed
  purple_stained_glass_pane drops from soul_lantern
  purple_terracotta drops from polished_andesite_stairs
  purple_wool drops from gray_candle
  purpur_block drops from stripped_oak_log
  purpur_pillar drops from donkey
  purpur_slab drops from deepslate_tiles
  purpur_stairs drops from birch_door
  quartz_block drops from mossy_cobblestone_slab
  quartz_bricks drops from pink_banner
  quartz_pillar drops from bee
  quartz_slab drops from mangrove_pressure_plate
  quartz_stairs drops from birch_pressure_plate
  rail drops from polished_granite_slab
  raw_copper_block drops from vex
  raw_gold_block drops from glass_pane
  raw_iron_block drops from cyan_glazed_terracotta
  redstone_block drops from stronghold_library
  redstone_lamp drops from trader_llama
  redstone_ore drops from ravager
  redstone_torch drops from frogspawn
  redstone_wire drops from brown
  red_banner drops from polished_blackstone_stairs
  red_bed drops from cracked_stone_bricks
  red_candle drops from mossy_stone_bricks
  red_candle_cake drops from waxed_oxidized_cut_copper_stairs
  red_carpet drops from cut_sandstone_slab
  red_concrete drops from polished_deepslate_slab
  red_concrete_powder drops from deepslate_gold_ore
  red_glazed_terracotta drops from gray_stained_glass
  red_mushroom drops from pink_carpet
  red_mushroom_block drops from tall_grass
  red_nether_bricks drops from oak_log
  red_nether_brick_slab drops from azalea_leaves
  red_nether_brick_stairs drops from green_concrete
  red_nether_brick_wall drops from crimson_fungus
  red_sand drops from village_temple
  red_sandstone drops from purpur_pillar
  red_sandstone_slab drops from lime_carpet
  red_sandstone_stairs drops from purpur_stairs
  red_sandstone_wall drops from blue_carpet
  red_stained_glass drops from farmer_gift
  red_stained_glass_pane drops from polished_diorite
  red_terracotta drops from large_amethyst_bud
  red_tulip drops from water_cauldron
  red_wool drops from rail
  reinforced_deepslate drops from ancient_city
  repeater drops from smooth_red_sandstone_slab
  respawn_anchor drops from smooth_basalt
  rooted_dirt drops from quartz_slab
  rose_bush drops from green_candle
  sand drops from light_blue_banner
  sandstone drops from orange_candle_cake
  sandstone_slab drops from birch_wood
  sandstone_stairs drops from dead_fire_coral
  sandstone_wall drops from prismarine
  scaffolding drops from red_glazed_terracotta
  sculk drops from end_city_treasure
  sculk_catalyst drops from dead_bubble_coral_fan
  sculk_shrieker drops from fisherman_gift
  sculk_vein drops from raw_copper_block
  seagrass drops from jungle_leaves
  sea_lantern drops from jungle_temple_dispenser
  sea_pickle drops from deepslate_brick_wall
  shroomlight drops from waxed_exposed_cut_copper_stairs
  skeleton_skull drops from phantom
  slime_block drops from orange_carpet
  small_amethyst_bud drops from small_dripleaf
  small_dripleaf drops from green_banner
  smithing_table drops from fire_coral_fan
  smoker drops from black_candle
  smooth_basalt drops from ice
  smooth_quartz drops from dead_horn_coral
  smooth_quartz_slab drops from black
  smooth_quartz_stairs drops from slime
  smooth_red_sandstone drops from magenta_stained_glass
  smooth_red_sandstone_slab drops from jungle_sapling
  smooth_red_sandstone_stairs drops from diorite_slab
  smooth_sandstone drops from polished_blackstone_slab
  smooth_sandstone_slab drops from elder_guardian
  smooth_sandstone_stairs drops from birch_fence
  smooth_stone drops from note_block
  smooth_stone_slab drops from pink_bed
  snow drops from medium_amethyst_bud
  snow_block drops from light_weighted_pressure_plate
  soul_campfire drops from oak_leaves
  soul_fire drops from red_sandstone_slab
  soul_lantern drops from potted_flowering_azalea_bush
  soul_sand drops from waxed_weathered_cut_copper
  soul_soil drops from chipped_anvil
  soul_torch drops from heavy_weighted_pressure_plate
  spawner drops from lily_of_the_valley
  sponge drops from potted_red_tulip
  spore_blossom drops from prismarine_wall
  spruce_button drops from blue_stained_glass
  spruce_door drops from dirt
  spruce_fence drops from prismarine_bricks
  spruce_fence_gate drops from flowering_azalea_leaves
  spruce_leaves drops from crimson_trapdoor
  spruce_log drops from warped_trapdoor
  spruce_planks drops from verdant_froglight
  spruce_pressure_plate drops from orange_glazed_terracotta
  spruce_sapling drops from illusioner
  spruce_sign drops from exposed_copper
  spruce_slab drops from red_terracotta
  spruce_stairs drops from fletcher_gift
  spruce_trapdoor drops from quartz_block
  spruce_wood drops from polished_blackstone_button
  sticky_piston drops from magma_block
  stone drops from purple
  stonecutter drops from stripped_crimson_hyphae
  stone_bricks drops from village_taiga_house
  stone_brick_slab drops from brewing_stand
  stone_brick_stairs drops from tripwire
  stone_brick_wall drops from light_blue_concrete_powder
  stone_button drops from red_wool
  stone_pressure_plate drops from spruce_pressure_plate
  stone_slab drops from seagrass
  stone_stairs drops from red_sandstone_stairs
  stripped_acacia_log drops from powder_snow_cauldron
  stripped_acacia_wood drops from chicken
  stripped_birch_log drops from zoglin
  stripped_birch_wood drops from tuff
  stripped_crimson_hyphae drops from warped_door
  stripped_crimson_stem drops from villager
  stripped_dark_oak_log drops from potted_red_mushroom
  stripped_dark_oak_wood drops from spruce_fence_gate
  stripped_jungle_log drops from magenta_candle
  stripped_jungle_wood drops from red_tulip
  stripped_mangrove_log drops from mud_brick_stairs
  stripped_mangrove_wood drops from repeater
  stripped_oak_log drops from yellow_concrete
  stripped_oak_wood drops from cyan_wool
  stripped_spruce_log drops from mangrove_slab
  stripped_spruce_wood drops from potted_azalea_bush
  stripped_warped_hyphae drops from cyan_terracotta
  stripped_warped_stem drops from cave_vines
  sugar_cane drops from deepslate_iron_ore
  sunflower drops from slime_block
  sweet_berry_bush drops from brown_mushroom_block
  tall_grass drops from waxed_cut_copper_slab
  tall_seagrass drops from mangrove_propagule
  target drops from light_blue_stained_glass
  terracotta drops from oxeye_daisy
  tinted_glass drops from cut_copper_slab
  tnt drops from fire
  torch drops from lightning_rod
  trapped_chest drops from skeleton_skull
  tripwire drops from mangrove_fence
  tripwire_hook drops from jungle_stairs
  tube_coral drops from stripped_birch_log
  tube_coral_block drops from stripped_acacia_wood
  tube_coral_fan drops from deepslate
  tuff drops from raw_iron_block
  turtle_egg drops from birch_slab
  twisting_vines drops from white_terracotta
  twisting_vines_plant drops from warped_fence
  verdant_froglight drops from waxed_exposed_cut_copper_slab
  vine drops from yellow_glazed_terracotta
  warped_button drops from black_concrete_powder
  warped_door drops from light_blue
  warped_fence drops from netherite_block
  warped_fence_gate drops from deepslate_emerald_ore
  warped_fungus drops from chiseled_red_sandstone
  warped_hyphae drops from red_concrete
  warped_nylium drops from pink_glazed_terracotta
  warped_planks drops from stripped_oak_wood
  warped_pressure_plate drops from beehive
  warped_roots drops from mossy_cobblestone_wall
  warped_sign drops from brick_wall
  warped_slab drops from leatherworker_gift
  warped_stairs drops from dead_tube_coral_block
  warped_stem drops from cyan_candle
  warped_trapdoor drops from dispenser
  warped_wart_block drops from cocoa
  water_cauldron drops from butcher_gift
  waxed_copper_block drops from weathered_cut_copper_slab
  waxed_cut_copper drops from light_gray_candle_cake
  waxed_cut_copper_slab drops from oak_planks
  waxed_cut_copper_stairs drops from librarian_gift
  waxed_exposed_copper drops from green_bed
  waxed_exposed_cut_copper drops from end_stone_brick_wall
  waxed_exposed_cut_copper_slab drops from cut_copper_stairs
  waxed_exposed_cut_copper_stairs drops from sea_lantern
  waxed_oxidized_copper drops from end_stone_bricks
  waxed_oxidized_cut_copper drops from light_gray_glazed_terracotta
  waxed_oxidized_cut_copper_slab drops from cyan_concrete
  waxed_oxidized_cut_copper_stairs drops from coarse_dirt
  waxed_weathered_copper drops from smooth_stone_slab
  waxed_weathered_cut_copper drops from dropper
  waxed_weathered_cut_copper_slab drops from orange_tulip
  waxed_weathered_cut_copper_stairs drops from sculk
  weathered_copper drops from blue_ice
  weathered_cut_copper drops from red_sandstone_wall
  weathered_cut_copper_slab drops from axolotl
  weathered_cut_copper_stairs drops from cut_red_sandstone
  weeping_vines drops from stripped_warped_hyphae
  weeping_vines_plant drops from potted_dead_bush
  wet_sponge drops from brick_stairs
  wheat drops from stripped_spruce_log
  white_banner drops from polished_blackstone_brick_slab
  white_bed drops from dead_brain_coral_block
  white_candle drops from mangrove_leaves
  white_candle_cake drops from white
  white_carpet drops from piglin
  white_concrete drops from mason_gift
  white_concrete_powder drops from nether_brick_fence
  white_glazed_terracotta drops from infested_cobblestone
  white_stained_glass drops from salmon
  white_stained_glass_pane drops from oak_fence_gate
  white_terracotta drops from purple_stained_glass
  white_tulip drops from purple_bed
  white_wool drops from crimson_planks
  wither_rose drops from stripped_jungle_wood
  wither_skeleton_skull drops from powered_rail
  yellow_banner drops from warped_pressure_plate
  yellow_bed drops from piglin_bartering
  yellow_candle drops from soul_torch
  yellow_candle_cake drops from warped_button
  yellow_carpet drops from magenta_candle_cake
  yellow_concrete drops from light_gray_concrete
  yellow_concrete_powder drops from blue
  yellow_glazed_terracotta drops from potted_wither_rose
  yellow_stained_glass drops from sunflower
  yellow_stained_glass_pane drops from light_blue_candle
  yellow_terracotta drops from vine
  yellow_wool drops from conduit
  zombie_head drops from grass
  abandoned_mineshaft drops from smooth_red_sandstone
  ancient_city drops from blue_concrete_powder
  ancient_city_ice_box drops from crimson_nylium
  bastion_bridge drops from crimson_sign
  bastion_hoglin_stable drops from potted_allium
  bastion_other drops from nether_gold_ore
  bastion_treasure drops from stray
  buried_treasure drops from budding_amethyst
  desert_pyramid drops from mangrove_wood
  end_city_treasure drops from activator_rail
  igloo_chest drops from potted_cactus
  jungle_temple drops from pink_stained_glass
  jungle_temple_dispenser drops from magenta_carpet
  nether_bridge drops from blue_wool
  pillager_outpost drops from oak_fence
  ruined_portal drops from spruce_sign
  shipwreck_map drops from sculk_vein
  shipwreck_supply drops from cave_spider
  shipwreck_treasure drops from wither_skeleton
  simple_dungeon drops from waxed_weathered_copper
  spawn_bonus_chest drops from village_snowy_house
  stronghold_corridor drops from waxed_copper_block
  stronghold_crossing drops from azalea
  stronghold_library drops from acacia_planks
  underwater_ruin_big drops from light_blue_carpet
  underwater_ruin_small drops from snow
  village_armorer drops from tube_coral
  village_butcher drops from parrot
  village_cartographer drops from igloo_chest
  village_desert_house drops from skeleton_horse
  village_fisher drops from trapped_chest
  village_fletcher drops from smooth_sandstone_slab
  village_mason drops from blue_candle_cake
  village_plains_house drops from bone_block
  village_savanna_house drops from tropical_fish
  village_shepherd drops from potted_fern
  village_snowy_house drops from birch_log
  village_taiga_house drops from green_stained_glass_pane
  village_tannery drops from polished_blackstone
  village_temple drops from lime_concrete
  village_toolsmith drops from acacia_door
  village_weaponsmith drops from pumpkin
  woodland_mansion drops from bubble_coral_block
  allay drops from gold_block
  armor_stand drops from comparator
  axolotl drops from yellow_bed
  bat drops from acacia_pressure_plate
  bee drops from carrots
  blaze drops from campfire
  cat drops from candle
  cave_spider drops from red_mushroom_block
  chicken drops from toolsmith_gift
  cod drops from chorus_flower
  cow drops from purple_candle_cake
  creeper drops from sea_pickle
  dolphin drops from orange_candle
  donkey drops from acacia_log
  drowned drops from fire_coral_block
  elder_guardian drops from cyan_bed
  enderman drops from polished_diorite_slab
  endermite drops from potted_blue_orchid
  ender_dragon drops from cobbled_deepslate
  evoker drops from infested_stone_bricks
  fox drops from white_glazed_terracotta
  frog drops from brown_candle_cake
  ghast drops from ruined_portal
  glow_squid drops from pillager_outpost
  goat drops from cat_morning_gift
  guardian drops from damaged_anvil
  hoglin drops from smooth_stone
  horse drops from tube_coral_block
  husk drops from crimson_stem
  illusioner drops from waxed_oxidized_cut_copper_slab
  iron_golem drops from purple_concrete
  llama drops from lime_stained_glass_pane
  magma_cube drops from simple_dungeon
  mooshroom drops from sheep
  mule drops from white_tulip
  ocelot drops from reinforced_deepslate
  panda drops from cyan
  parrot drops from cracked_deepslate_tiles
  phantom drops from jungle_door
  pig drops from mangrove_planks
  piglin drops from brown_glazed_terracotta
  piglin_brute drops from stone_pressure_plate
  pillager drops from magma_cube
  polar_bear drops from polished_andesite_slab
  pufferfish drops from cow
  rabbit drops from white_stained_glass_pane
  ravager drops from iron_bars
  salmon drops from chiseled_nether_bricks
  sheep drops from lily_pad
  black drops from strider
  blue drops from smooth_red_sandstone_stairs
  brown drops from black_concrete
  cyan drops from nether_portal
  gray drops from acacia_wood
  green drops from potted_cornflower
  light_blue drops from acacia_button
  light_gray drops from lime_concrete_powder
  lime drops from wither
  magenta drops from tinted_glass
  orange drops from light_blue_terracotta
  pink drops from stripped_jungle_log
  purple drops from shipwreck_map
  red drops from twisting_vines
  white drops from wither_skeleton_skull
  yellow drops from large_fern
  shulker drops from chain
  silverfish drops from beacon
  skeleton drops from wither_rose
  skeleton_horse drops from snow_block
  slime drops from bricks
  snow_golem drops from daylight_detector
  spider drops from red_sandstone
  squid drops from ghast
  stray drops from brown_wool
  strider drops from ochre_froglight
  tadpole drops from shipwreck_supply
  trader_llama drops from iron_trapdoor
  tropical_fish drops from big_dripleaf_stem
  turtle drops from brain_coral_fan
  vex drops from purple_candle
  villager drops from grindstone
  vindicator drops from purple_wool
  wandering_trader drops from dripstone_block
  warden drops from buried_treasure
  witch drops from acacia_fence
  wither drops from birch_button
  wither_skeleton drops from spruce_door
  wolf drops from nether_wart_block
  zoglin drops from clay
  zombie drops from lime_wool
  zombie_horse drops from magenta_concrete
  zombie_villager drops from ender_dragon
  zombified_piglin drops from hay_block
  cat_morning_gift drops from mud_brick_slab
  fishing drops from stripped_acacia_log
  fish drops from glow_squid
  junk drops from smooth_quartz_stairs
  treasure drops from orange_wool
  armorer_gift drops from raw_gold_block
  butcher_gift drops from potted_bamboo
  cartographer_gift drops from creeper_head
  cleric_gift drops from purple_carpet
  farmer_gift drops from magenta_banner
  fisherman_gift drops from copper_ore
  fletcher_gift drops from twisting_vines_plant
  leatherworker_gift drops from dark_oak_stairs
  librarian_gift drops from purpur_slab
  mason_gift drops from observer
  shepherd_gift drops from stone
  toolsmith_gift drops from deepslate_bricks
  weaponsmith_gift drops from crimson_pressure_plate
  piglin_bartering drops from iron_golem
  `;
}
